name: External Libraries

on:
  push:
    branches:
      - develop
      # Include all release branches.
      - '[0-9]+.[0-9]+'
  pull_request:

jobs:
  unit-test:
    name: "Unit test / ${{ matrix.lib }}: PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/${{ matrix.lib }}
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '5.6']
        lib: ['common', 'optimizer']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, iconv, json, libxml
          tools: composer:v1, cs2pr

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Configure Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-ext-libs-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-ext-libs-
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install

      # Scan the logs for failing tests and surface that information by creating annotations and log file decorations.
      - name: Setup problem matcher to provide annotations for PHPUnit
        # The JSON file is provided by the `shivammathur/setup-php` action. See https://github.com/shivammathur/setup-php#problem-matchers.
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Detect coding standard violations (PHPCS)
        run: vendor/bin/phpcs -q --report=checkstyle --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1 | cs2pr --graceful-warnings

      - name: Static Analysis (PHPStan)
        if: ${{ matrix.php != '5.6' }}
        run: vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr

      - name: Run tests
        run: composer unit
